ipmo PKI
$name = [GUID]::NewGuid()
$cerFile = "$env:TEMP\$name.cer"
$certs = Get-ChildItem Cert:\LocalMachine\My -DnsName localhost -SSLServerAuthentication |
? {($_.FriendlyName -eq 'IIS Express Development Certificate') -and
($_.SignatureAlgorithm.FriendlyName -ieq 'sha256RSA') -and
($_.EnhancedKeyUsageList.Count -eq 1)}
if ($certs.Count -eq 0)
{
    Write-Error 'Cannot find any SHA256 certificate generated by IIS Express.
    Please make sure that the latest version of IIS Express is installed.'
}
else
{
    foreach ($cert in $certs)
    {
        Export-Certificate -Cert $cert.PSPath -FilePath $cerFile -Type CERT | Out-Null
        Import-Certificate -FilePath $cerFile -CertStoreLocation Cert:\CurrentUser\Root | Out-Null
        Remove-Item $cerFile -Force
    }
    Write-Host 'Successfully installed the certificate to
    Trusted Root Certification Authorities of the current user.'
}